//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilLux.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtilLux.App.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string AddKeyFormat {
            get {
                return ResourceManager.GetString("AddKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Sylvia Beck.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position: {0}.
        /// </summary>
        internal static string CurrentPositionFormat {
            get {
                return ResourceManager.GetString("CurrentPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get new version.
        /// </summary>
        internal static string GetNewVersion {
            get {
                return ResourceManager.GetString("GetNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to stop the UtilLux service before installing the new version.
        /// </summary>
        internal static string GetNewVersionHint {
            get {
                return ResourceManager.GetString("GetNewVersionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string KeyCode0 {
            get {
                return ResourceManager.GetString("KeyCode0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string KeyCode1 {
            get {
                return ResourceManager.GetString("KeyCode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string KeyCode2 {
            get {
                return ResourceManager.GetString("KeyCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string KeyCode3 {
            get {
                return ResourceManager.GetString("KeyCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string KeyCode4 {
            get {
                return ResourceManager.GetString("KeyCode4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string KeyCode5 {
            get {
                return ResourceManager.GetString("KeyCode5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string KeyCode6 {
            get {
                return ResourceManager.GetString("KeyCode6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string KeyCode7 {
            get {
                return ResourceManager.GetString("KeyCode7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string KeyCode8 {
            get {
                return ResourceManager.GetString("KeyCode8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string KeyCode9 {
            get {
                return ResourceManager.GetString("KeyCode9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string KeyCodeA {
            get {
                return ResourceManager.GetString("KeyCodeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string KeyCodeB {
            get {
                return ResourceManager.GetString("KeyCodeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `.
        /// </summary>
        internal static string KeyCodeBackQuote {
            get {
                return ResourceManager.GetString("KeyCodeBackQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        internal static string KeyCodeBackslash {
            get {
                return ResourceManager.GetString("KeyCodeBackslash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string KeyCodeC {
            get {
                return ResourceManager.GetString("KeyCodeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string KeyCodeComma {
            get {
                return ResourceManager.GetString("KeyCodeComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string KeyCodeD {
            get {
                return ResourceManager.GetString("KeyCodeD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string KeyCodeE {
            get {
                return ResourceManager.GetString("KeyCodeE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string KeyCodeEquals {
            get {
                return ResourceManager.GetString("KeyCodeEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string KeyCodeF {
            get {
                return ResourceManager.GetString("KeyCodeF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string KeyCodeF1 {
            get {
                return ResourceManager.GetString("KeyCodeF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F10.
        /// </summary>
        internal static string KeyCodeF10 {
            get {
                return ResourceManager.GetString("KeyCodeF10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F11.
        /// </summary>
        internal static string KeyCodeF11 {
            get {
                return ResourceManager.GetString("KeyCodeF11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F12.
        /// </summary>
        internal static string KeyCodeF12 {
            get {
                return ResourceManager.GetString("KeyCodeF12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        internal static string KeyCodeF2 {
            get {
                return ResourceManager.GetString("KeyCodeF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3.
        /// </summary>
        internal static string KeyCodeF3 {
            get {
                return ResourceManager.GetString("KeyCodeF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4.
        /// </summary>
        internal static string KeyCodeF4 {
            get {
                return ResourceManager.GetString("KeyCodeF4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        internal static string KeyCodeF5 {
            get {
                return ResourceManager.GetString("KeyCodeF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6.
        /// </summary>
        internal static string KeyCodeF6 {
            get {
                return ResourceManager.GetString("KeyCodeF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7.
        /// </summary>
        internal static string KeyCodeF7 {
            get {
                return ResourceManager.GetString("KeyCodeF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8.
        /// </summary>
        internal static string KeyCodeF8 {
            get {
                return ResourceManager.GetString("KeyCodeF8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        internal static string KeyCodeF9 {
            get {
                return ResourceManager.GetString("KeyCodeF9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string KeyCodeG {
            get {
                return ResourceManager.GetString("KeyCodeG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        internal static string KeyCodeH {
            get {
                return ResourceManager.GetString("KeyCodeH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string KeyCodeI {
            get {
                return ResourceManager.GetString("KeyCodeI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J.
        /// </summary>
        internal static string KeyCodeJ {
            get {
                return ResourceManager.GetString("KeyCodeJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string KeyCodeK {
            get {
                return ResourceManager.GetString("KeyCodeK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string KeyCodeL {
            get {
                return ResourceManager.GetString("KeyCodeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string KeyCodeM {
            get {
                return ResourceManager.GetString("KeyCodeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string KeyCodeMinus {
            get {
                return ResourceManager.GetString("KeyCodeMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string KeyCodeN {
            get {
                return ResourceManager.GetString("KeyCodeN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string KeyCodeO {
            get {
                return ResourceManager.GetString("KeyCodeO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string KeyCodeP {
            get {
                return ResourceManager.GetString("KeyCodeP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string KeyCodePeriod {
            get {
                return ResourceManager.GetString("KeyCodePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        internal static string KeyCodeQ {
            get {
                return ResourceManager.GetString("KeyCodeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string KeyCodeQuote {
            get {
                return ResourceManager.GetString("KeyCodeQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string KeyCodeR {
            get {
                return ResourceManager.GetString("KeyCodeR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string KeyCodeS {
            get {
                return ResourceManager.GetString("KeyCodeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string KeyCodeSemicolon {
            get {
                return ResourceManager.GetString("KeyCodeSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string KeyCodeSlash {
            get {
                return ResourceManager.GetString("KeyCodeSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string KeyCodeT {
            get {
                return ResourceManager.GetString("KeyCodeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        internal static string KeyCodeU {
            get {
                return ResourceManager.GetString("KeyCodeU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string KeyCodeV {
            get {
                return ResourceManager.GetString("KeyCodeV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string KeyCodeW {
            get {
                return ResourceManager.GetString("KeyCodeW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string KeyCodeX {
            get {
                return ResourceManager.GetString("KeyCodeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string KeyCodeY {
            get {
                return ResourceManager.GetString("KeyCodeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string KeyCodeZ {
            get {
                return ResourceManager.GetString("KeyCodeZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Alt.
        /// </summary>
        internal static string ModifierKeyAlt {
            get {
                return ResourceManager.GetString("ModifierKeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Command.
        /// </summary>
        internal static string ModifierKeyCommand {
            get {
                return ResourceManager.GetString("ModifierKeyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Ctrl.
        /// </summary>
        internal static string ModifierKeyCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Alt.
        /// </summary>
        internal static string ModifierKeyLeftAlt {
            get {
                return ResourceManager.GetString("ModifierKeyLeftAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Command.
        /// </summary>
        internal static string ModifierKeyLeftCommand {
            get {
                return ResourceManager.GetString("ModifierKeyLeftCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ctrl.
        /// </summary>
        internal static string ModifierKeyLeftCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyLeftCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Option.
        /// </summary>
        internal static string ModifierKeyLeftOption {
            get {
                return ResourceManager.GetString("ModifierKeyLeftOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Shift.
        /// </summary>
        internal static string ModifierKeyLeftShift {
            get {
                return ResourceManager.GetString("ModifierKeyLeftShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Super.
        /// </summary>
        internal static string ModifierKeyLeftSuper {
            get {
                return ResourceManager.GetString("ModifierKeyLeftSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Win.
        /// </summary>
        internal static string ModifierKeyLeftWin {
            get {
                return ResourceManager.GetString("ModifierKeyLeftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no key&gt;.
        /// </summary>
        internal static string ModifierKeyNone {
            get {
                return ResourceManager.GetString("ModifierKeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Option.
        /// </summary>
        internal static string ModifierKeyOption {
            get {
                return ResourceManager.GetString("ModifierKeyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Alt.
        /// </summary>
        internal static string ModifierKeyRightAlt {
            get {
                return ResourceManager.GetString("ModifierKeyRightAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Command.
        /// </summary>
        internal static string ModifierKeyRightCommand {
            get {
                return ResourceManager.GetString("ModifierKeyRightCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ctrl.
        /// </summary>
        internal static string ModifierKeyRightCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyRightCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Option.
        /// </summary>
        internal static string ModifierKeyRightOption {
            get {
                return ResourceManager.GetString("ModifierKeyRightOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Shift.
        /// </summary>
        internal static string ModifierKeyRightShift {
            get {
                return ResourceManager.GetString("ModifierKeyRightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Super.
        /// </summary>
        internal static string ModifierKeyRightSuper {
            get {
                return ResourceManager.GetString("ModifierKeyRightSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Win.
        /// </summary>
        internal static string ModifierKeyRightWin {
            get {
                return ResourceManager.GetString("ModifierKeyRightWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier keys must be different in each row.
        /// </summary>
        internal static string ModifierKeysAreSame {
            get {
                return ResourceManager.GetString("ModifierKeysAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string ModifierKeySeparator {
            get {
                return ResourceManager.GetString("ModifierKeySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Shift.
        /// </summary>
        internal static string ModifierKeyShift {
            get {
                return ResourceManager.GetString("ModifierKeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Super.
        /// </summary>
        internal static string ModifierKeySuper {
            get {
                return ResourceManager.GetString("ModifierKeySuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Win.
        /// </summary>
        internal static string ModifierKeyWin {
            get {
                return ResourceManager.GetString("ModifierKeyWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        internal static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0}.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version!.
        /// </summary>
        internal static string NoNewVersions {
            get {
                return ResourceManager.GetString("NoNewVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you input the number then press &apos;Enter&apos; to apply changes.
        /// </summary>
        internal static string NumberBoxHint {
            get {
                return ResourceManager.GetString("NumberBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox.
        /// </summary>
        internal static string Sandbox {
            get {
                return ResourceManager.GetString("Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox is a where you can test out your changes in settings and preferences.
        /// </summary>
        internal static string SandboxInfo {
            get {
                return ResourceManager.GetString("SandboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Maximum Keys.
        /// </summary>
        internal static string SleepMax {
            get {
                return ResourceManager.GetString("SleepMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Max Key.
        /// </summary>
        internal static string SleepMaxExecutionKey {
            get {
                return ResourceManager.GetString("SleepMaxExecutionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Sleep Time.
        /// </summary>
        internal static string SleepMaxValue {
            get {
                return ResourceManager.GetString("SleepMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Minimum Keys.
        /// </summary>
        internal static string SleepMin {
            get {
                return ResourceManager.GetString("SleepMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Min Key.
        /// </summary>
        internal static string SleepMinExecutionKey {
            get {
                return ResourceManager.GetString("SleepMinExecutionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Sleep Time.
        /// </summary>
        internal static string SleepMinValue {
            get {
                return ResourceManager.GetString("SleepMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Settings:.
        /// </summary>
        internal static string SleepSettings {
            get {
                return ResourceManager.GetString("SleepSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the service when you log in.
        /// </summary>
        internal static string StartOnLogIn {
            get {
                return ResourceManager.GetString("StartOnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UtilLux.
        /// </summary>
        internal static string UtilLux {
            get {
                return ResourceManager.GetString("UtilLux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UtilLux service is not running.
        /// </summary>
        internal static string UtilLuxServiceNotRunning {
            get {
                return ResourceManager.GetString("UtilLuxServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UtilLux service is running.
        /// </summary>
        internal static string UtilLuxServiceRunning {
            get {
                return ResourceManager.GetString("UtilLuxServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UtilLux service is shutting down.
        /// </summary>
        internal static string UtilLuxServiceShuttingDown {
            get {
                return ResourceManager.GetString("UtilLuxServiceShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string ValidationNameEmpty {
            get {
                return ResourceManager.GetString("ValidationNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the docs.
        /// </summary>
        internal static string ViewDocs {
            get {
                return ResourceManager.GetString("ViewDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UtilLux Settings.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
